### ISSUE TITLE
Question about freelancing.

### ISSUE THREAD

**Issue by yackermann** [maban/ama#1]
Hey Anna. First of all, thank you for great Jekyll tuts you wrote at 24ways. It's really kick-started me.

Now the questions: 

I want to do some freelance, but I don't have confidence in my skills.
- How do you know if you are ready?
- What pro tips could you give me/us in freelance?
- What freelance platform do you use?
- What tracking software do you use(i.e. Trello)?
- How competitive freelance market? 
- Maybe what books would you recommend on webdev?
- What is your favorite tea?

Sorry for so many questions. 

Best regards. Yuriy.

**Comment by maban** [comment]
Hi Yuriy, lots of questions! I'll try to do them justice.

**How do you know if you are ready?**

Psychologically, I don't think it's easy to ever feel fully ready. But there are some things you can do to prepare yourself that will help, like building up a financial buffer that you can fall back on if work dries up and finding a decent accountant and getting advice from them on whether they think you are ready.

You need to be reasonably confident in your abilities, but at the same time, not afraid to say if there's something you don't know yet (clients will understand).

It might be a good idea to take on a small project alongside what you're currently doing, just to get a feel for how managing your own project works.

**What pro tips could you give me/us in freelance?**

I wrote a whole blog post on this which you might find useful: http://maban.co.uk/93/

**What freelance platform do you use?**

The only software I really use is FreeAgent to help me manage my accounts and file taxes. Other options are Harvest and Xero.

**What tracking software do you use(i.e. Trello)?**

I use whatever the client I'm working with uses, so that might be Jira, Trello (my favourite), Basecamp, or something internal. They're still quite heavygoing tools though, so I use Wonderlist for all my personal and adminy tasks.

For tracking time, I used an app called Timepost, but that's been discontinued. That was useful for when I was working on multiple projects at once, and billing hourly. For the past few years, I've just been tracking time in my calendar because the smallest amount of time I will be working on a project and billing for is a full day.

**How competitive freelance market?**

It depends what you're specialising in and where you're working (or willing to commute to). There always seems to be front-end work in London, but I'm not sure about the markets elsewhere, or for different roles. If you're worried about it at all, there seems to be a very competitive _recruiter_ market (based on the number of cold calls I get) so they might be able to help find you work.

**Maybe what books would you recommend on webdev?**

I love Jon Duckett's books, [HTML & CSS](http://www.htmlandcssbook.com/) and [Javascript & jQuery](http://javascriptbook.com/). Even though I've been writing HTML and CSS for over 10 years, I still reference that book when I can't remember the correct syntax for something. It's a vital foundation. Most other stuff I prefer to look up online because it changes so quickly.

**What is your favorite tea?**

[Yorkshire Tea](https://www.yorkshiretea.co.uk/). And [here's how I make it](http://teamethod.co.uk/).

**Comment by yackermann** [comment]
@maban Thanks a lot. I never even thought about financial buffer. And looking forward to read your blogpost tonight.

Under freelance platform I meant something like https://www.freelancer.com/ or https://www.upwork.com/, or are you more email/website face-to-face opportunist

Nice to see people using XERO(Hello from NZ). I see every day people who work there(Cause they all were XERO shirts XD). They like invaded Wellington.

And thanks for tea recipe. It reminds me of Orwell's "A Nice Cup of Tea" essay http://www.booksatoz.com/witsend/tea/orwell.htm

**Comment by maban** [comment]
> Under freelance platform I meant something like https://www.freelancer.com/ or https://www.upwork.com/, or are you more email/website face-to-face opportunist

Nah, I'm more face-to-face. Most work comes through word of mouth and recommendations from designers or other front-end devs.

**Comment by yackermann** [comment]
@maban *)
