### ISSUE TITLE
What’s your favorite web conference?

### ISSUE THREAD

**Issue by zachleat** [maban/ama#3]
As a speaker or an attendee. And why?

**Comment by maban** [comment]
Oooh, tricky one!

…

As a speaker, [ffconf](http://lanyrd.com/2012/full-frontal/). It was a really tough one to prepare for mentally because the speakers the year before had set a very high bar, I had a lot of friends and colleagues in the audience, and I felt like a fraud speaking about not-javascript at a javascript conference. Remy and Julie were so wonderful at looking after me and Julie sat with me before my talk and helped me calm down because I was starting to freak out a bit! But it was such a wonderful feeling having done it. So from a personal achievement point of view, that was my favourite.

As an attendee, I loved going to [Build 2012](http://lanyrd.com/2012/build/) because I went on the axe restoration workshop which was really, really fun and not about the web and I got to chop wood in a forest. And I got to keep the axe, which you can't really beat as conference swag goes.

**Comment by zachleat** [comment]
An Axe restoration workshop!? Amazing!

Thanks!

**Comment by andymcmillan** [comment]
Ooh, thanks for the kind words about Build 2012 :)
