### ISSUE TITLE
How does the increasing popularity of "web apps" make you feel?

### ISSUE THREAD

**Issue by jaicab** [maban/ama#5]
I know you love your console browsers so I'm confident you have a mindset more related with progressive enhancement than web apps, as I do. But the scene seems to be moving towards these complex, sometimes over-engineered solutions like Angular or React instead of using a PE approach.

So I wonder: how does that makes you feel or where do you stand on this? Do you feel it's going to be a necessary skill as a frontend developer?

**Comment by maban** [comment]
These JS frameworks make me nervous, but maybe that's because I don't know enough about them. I've heard they can be written in such a way that makes them degrade gracefully if browser functionality is missing, but my concern isn't so much with the technology, and more with the attitude of developers. I think many don't think of PE as that important, or feel that it gets in the way of shipping features.

When I'm building things, I want things to still be functional if JS isn't working or if I'm using a less capable browser. But I also appreciate the pressure of doing that with very tight deadlines, or an iterative process where you don't know what the final thing is going to be until right before it launches. I don't want to dismiss developers who don't prioritise this as being lazy, because maybe they do care, but their team's focus is on getting things out of the door.

At the end of the day though, not building things using a PE approach will lose sales/visitors, so it will eventually come back to bite the developers who go against the grain of the web.

**Comment by jaicab** [comment]
Great answer, thanks a lot Anna!
