### ISSUE TITLE
How did you land your first client?

### ISSUE THREAD

**Issue by PauliusKK** [maban/ama#6]
Hey Anna,

I'm starting out as a freelance front-end developer and just wondering, how did you land your first client?

Thanks in advance, have a wonderful day!

Cheers,
Paulius

**Comment by maban** [comment]
Hi Paulius,

I guess my first client was my school – they had a really basic website and I wrote a letter to the headteacher explaining why it needed redesigning, and why I thought I was the right person to do it. She very kindly let me go ahead with the build, and I gave a presentation to the governors to win them round too, and get their input on what they wanted improved on the site. I didn't get paid for it, but they did pay for a conference ticket for me when I asked if I could have time off school to go.

Most people get their first client through a friend or family contact, and this is a nice way of easing into freelance work. But you still have to treat the client-freelancer relationship very seriously – not just for practice, but also because these projects can turn bad if there's no contract in place or realistic expectation of what can be delivered. Your first project will probably take you longer than you think – so take that into account. It took me about a year of doing client work before I got estimates right.
