### ISSUE TITLE
Debugging on consoles?

### ISSUE THREAD

**Issue by RafaelKeramidas** [maban/ama#7]
Hey Anna,

First of all, thanks for all the work and research you shared on console browsers, those kind of resources are rare but so useful for making the web better for everyone! 

I think you probably faced the same issue as I currently have. A problem on a website that only appears on a particular console browser. In my case, it's on a React-Redux app on PS4. Some functionalities are simply broken, they do not give any feedback making me think that there might be a JavaScript error somewhere that is unique to the PS4.

I tried a couple of remote debugging tools such as GhostLab, VorlonJS or JSConsole, but none of those were a big help. I also blindly made changes with the hope that it would resolve the issues by changing my babel presets and adding polyfills but that didn't work as well. I don't really know what else to try.

How would debug issues on a console? Any particular method or tools you are using?

Cheers!
Raf

**Comment by maban** [comment]
Hi, Raf! Great question 😄 

These are the hardest things to pin down! Something I'll often end up doing is a kind of process of elimination where I isolate the code, and either slowly take stuff out until it works, or slowly add stuff in until it doesn't. That way, I can see which specific part of the code is causing it to break. Sometimes it'll help to have this as a Codepen link or something so you can easily make changes on your computer and re-test.

It's likely to be that the PS4's browser doesn't support some specific bits – have a look at https://html5test.com/ on the browser to get a summary. Although, take those results with a pinch of salt as there are _some_ bits of functionality that report that they are supported but aren't. (Like Geolocation on some console browsers). That's especially a problem if you're using feature sniffing, because it'll say "yeah, I support that", but it doesn't, or not fully.

I hope you're able to find out what it's unhappy about!

**Comment by RafaelKeramidas** [comment]
Thanks for the reply and sorry for my late response, I totally missed the Github notification :smile:

I went down the road of removing bits of code and randomly decided to throw the babel-polyfill in and it worked. I then added the bits back and it broke again. I finally found out that the module React-Intl was causing the second breakage because older versions of WebKit don't support Intl. This is also impacting the Safari browser on iOS 9 and below. Threw an Intl polyfill in and everything is now working fine on the PS4 and iOS 9. 

So my issue was a combination of multiple missing features that were solved by loading Babel-Polyfill and Intl.js. Little side note for people who have the same issue: the Intl polyfill is quite heavy, loading it conditionally is strongly recommended :smile:

Oh, and I realized that the mistake I made with VorlonJS was that I stupidly loaded it just after my bundle (it was before my daily caffeine dose), putting it just before everything else makes it work fine. Very handy tool, would absolutely recommend for scenarios when you don't have debugging tools available.

Thanks again for your response and help, I really appreciate it!

Raf
